### ISSUE TITLE
[NextJS ReactJS] Make Add modal (Name field) from text field to autocomplete field

### ISSUE THREAD

**Issue by aecuto** [aecuto/doo-anime#2]
![image](https://github.com/aecuto/watching-list/assets/16747081/0ecd8846-521e-49d6-b510-3ab02fa31c2e)

Call getAnimeSearch in `src/app/services/jikan.ts`  for autocomplete field

**Comment by burhanharoon** [comment]
That's a good idea, @aecuto assign this to me and I'll get this done! Thank you.
