### ISSUE TITLE
[nextjs reactjs] redesign anime card  and refactor

### ISSUE THREAD

**Issue by aecuto** [aecuto/doo-anime#3]
make it easy to use 

![image](https://github.com/aecuto/watching-list/assets/16747081/d152c589-9f37-4084-be6e-53890bec44d9)

**Comment by burhanharoon** [comment]
Hi @aecuto, please assign this issue to me, I would love to contribute to this. Thank you!

**Comment by burhanharoon** [comment]
Maybe we can add a rating system, where the user can rate an anime based on how it is. What do you say @aecuto ?

**Comment by aecuto** [comment]
its good idea but right now I have not an api for rating
